@php
$countries = [

    // 🌎 América del Norte y Caribe
    ['name' => 'United States', 'code' => '+1'],
    ['name' => 'Canada', 'code' => '+1'],
    ['name' => 'Puerto Rico', 'code' => '+1-787'],
    ['name' => 'Puerto Rico (alt)', 'code' => '+1-939'],
    ['name' => 'Guam', 'code' => '+1-671'],
    ['name' => 'Northern Mariana Islands', 'code' => '+1-670'],
    ['name' => 'US Virgin Islands', 'code' => '+1-340'],
    ['name' => 'American Samoa', 'code' => '+1-684'],
    ['name' => 'Anguilla', 'code' => '+1-264'],
    ['name' => 'Antigua and Barbuda', 'code' => '+1-268'],
    ['name' => 'Bahamas', 'code' => '+1-242'],
    ['name' => 'Barbados', 'code' => '+1-246'],
    ['name' => 'Bermuda', 'code' => '+1-441'],
    ['name' => 'British Virgin Islands', 'code' => '+1-284'],
    ['name' => 'Cayman Islands', 'code' => '+1-345'],
    ['name' => 'Dominica', 'code' => '+1-767'],
    ['name' => 'Dominican Republic', 'code' => '+1-809'],
    ['name' => 'Dominican Republic (alt)', 'code' => '+1-829'],
    ['name' => 'Dominican Republic (alt)', 'code' => '+1-849'],
    ['name' => 'Grenada', 'code' => '+1-473'],
    ['name' => 'Jamaica', 'code' => '+1-876'],
    ['name' => 'Montserrat', 'code' => '+1-664'],
    ['name' => 'Saint Kitts and Nevis', 'code' => '+1-869'],
    ['name' => 'Saint Lucia', 'code' => '+1-758'],
    ['name' => 'Saint Vincent and the Grenadines', 'code' => '+1-784'],
    ['name' => 'Sint Maarten', 'code' => '+1-721'],
    ['name' => 'Trinidad and Tobago', 'code' => '+1-868'],
    ['name' => 'Turks and Caicos Islands', 'code' => '+1-649'],

    // 🌎 Latinoamérica
    ['name' => 'Mexico', 'code' => '+52'],
    ['name' => 'Belize', 'code' => '+501'],
    ['name' => 'Costa Rica', 'code' => '+506', 'fav' => true],
    ['name' => 'El Salvador', 'code' => '+503'],
    ['name' => 'Guatemala', 'code' => '+502'],
    ['name' => 'Honduras', 'code' => '+504'],
    ['name' => 'Nicaragua', 'code' => '+505'],
    ['name' => 'Panama', 'code' => '+507'],
    ['name' => 'Argentina', 'code' => '+54'],
    ['name' => 'Bolivia', 'code' => '+591'],
    ['name' => 'Brazil', 'code' => '+55'],
    ['name' => 'Chile', 'code' => '+56'],
    ['name' => 'Colombia', 'code' => '+57'],
    ['name' => 'Ecuador', 'code' => '+593'],
    ['name' => 'Guyana', 'code' => '+592'],
    ['name' => 'Paraguay', 'code' => '+595'],
    ['name' => 'Peru', 'code' => '+51'],
    ['name' => 'Suriname', 'code' => '+597'],
    ['name' => 'Uruguay', 'code' => '+598'],
    ['name' => 'Venezuela', 'code' => '+58'],

    // 🌍 Europa
    ['name' => 'Albania', 'code' => '+355'],
    ['name' => 'Andorra', 'code' => '+376'],
    ['name' => 'Austria', 'code' => '+43'],
    ['name' => 'Belarus', 'code' => '+375'],
    ['name' => 'Belgium', 'code' => '+32'],
    ['name' => 'Bosnia and Herzegovina', 'code' => '+387'],
    ['name' => 'Bulgaria', 'code' => '+359'],
    ['name' => 'Croatia', 'code' => '+385'],
    ['name' => 'Cyprus', 'code' => '+357'],
    ['name' => 'Czechia', 'code' => '+420'],
    ['name' => 'Denmark', 'code' => '+45'],
    ['name' => 'Estonia', 'code' => '+372'],
    ['name' => 'Finland', 'code' => '+358'],
    ['name' => 'France', 'code' => '+33'],
    ['name' => 'Germany', 'code' => '+49'],
    ['name' => 'Greece', 'code' => '+30'],
    ['name' => 'Hungary', 'code' => '+36'],
    ['name' => 'Iceland', 'code' => '+354'],
    ['name' => 'Ireland', 'code' => '+353'],
    ['name' => 'Italy', 'code' => '+39'],
    ['name' => 'Kosovo', 'code' => '+383'],
    ['name' => 'Latvia', 'code' => '+371'],
    ['name' => 'Lithuania', 'code' => '+370'],
    ['name' => 'Luxembourg', 'code' => '+352'],
    ['name' => 'Malta', 'code' => '+356'],
    ['name' => 'Monaco', 'code' => '+377'],
    ['name' => 'Montenegro', 'code' => '+382'],
    ['name' => 'Netherlands', 'code' => '+31'],
    ['name' => 'North Macedonia', 'code' => '+389'],
    ['name' => 'Norway', 'code' => '+47'],
    ['name' => 'Poland', 'code' => '+48'],
    ['name' => 'Portugal', 'code' => '+351'],
    ['name' => 'Romania', 'code' => '+40'],
    ['name' => 'Russia', 'code' => '+7'],
    ['name' => 'San Marino', 'code' => '+378'],
    ['name' => 'Serbia', 'code' => '+381'],
    ['name' => 'Slovakia', 'code' => '+421'],
    ['name' => 'Slovenia', 'code' => '+386'],
    ['name' => 'Spain', 'code' => '+34'],
    ['name' => 'Sweden', 'code' => '+46'],
    ['name' => 'Switzerland', 'code' => '+41'],
    ['name' => 'Turkey', 'code' => '+90'],
    ['name' => 'Ukraine', 'code' => '+380'],
    ['name' => 'United Kingdom', 'code' => '+44'],
    ['name' => 'Vatican City', 'code' => '+379'],

    // 🌍 África
    ['name' => 'Algeria', 'code' => '+213'],
    ['name' => 'Angola', 'code' => '+244'],
    ['name' => 'Benin', 'code' => '+229'],
    ['name' => 'Botswana', 'code' => '+267'],
    ['name' => 'Burkina Faso', 'code' => '+226'],
    ['name' => 'Burundi', 'code' => '+257'],
    ['name' => 'Cameroon', 'code' => '+237'],
    ['name' => 'Cape Verde', 'code' => '+238'],
    ['name' => 'Central African Republic', 'code' => '+236'],
    ['name' => 'Chad', 'code' => '+235'],
    ['name' => 'Comoros', 'code' => '+269'],
    ['name' => 'Congo (Republic)', 'code' => '+242'],
    ['name' => 'Congo (DRC)', 'code' => '+243'],
    ['name' => 'Djibouti', 'code' => '+253'],
    ['name' => 'Egypt', 'code' => '+20'],
    ['name' => 'Equatorial Guinea', 'code' => '+240'],
    ['name' => 'Eritrea', 'code' => '+291'],
    ['name' => 'Eswatini', 'code' => '+268'],
    ['name' => 'Ethiopia', 'code' => '+251'],
    ['name' => 'Gabon', 'code' => '+241'],
    ['name' => 'Gambia', 'code' => '+220'],
    ['name' => 'Ghana', 'code' => '+233'],
    ['name' => 'Guinea', 'code' => '+224'],
    ['name' => 'Guinea-Bissau', 'code' => '+245'],
    ['name' => 'Ivory Coast', 'code' => '+225'],
    ['name' => 'Kenya', 'code' => '+254'],
    ['name' => 'Lesotho', 'code' => '+266'],
    ['name' => 'Liberia', 'code' => '+231'],
    ['name' => 'Libya', 'code' => '+218'],
    ['name' => 'Madagascar', 'code' => '+261'],
    ['name' => 'Malawi', 'code' => '+265'],
    ['name' => 'Mali', 'code' => '+223'],
    ['name' => 'Mauritania', 'code' => '+222'],
    ['name' => 'Mauritius', 'code' => '+230'],
    ['name' => 'Morocco', 'code' => '+212'],
    ['name' => 'Mozambique', 'code' => '+258'],
    ['name' => 'Namibia', 'code' => '+264'],
    ['name' => 'Niger', 'code' => '+227'],
    ['name' => 'Nigeria', 'code' => '+234'],
    ['name' => 'Rwanda', 'code' => '+250'],
    ['name' => 'Sao Tome and Principe', 'code' => '+239'],
    ['name' => 'Senegal', 'code' => '+221'],
    ['name' => 'Seychelles', 'code' => '+248'],
    ['name' => 'Sierra Leone', 'code' => '+232'],
    ['name' => 'Somalia', 'code' => '+252'],
    ['name' => 'South Africa', 'code' => '+27'],
    ['name' => 'South Sudan', 'code' => '+211'],
    ['name' => 'Sudan', 'code' => '+249'],
    ['name' => 'Tanzania', 'code' => '+255'],
    ['name' => 'Togo', 'code' => '+228'],
    ['name' => 'Tunisia', 'code' => '+216'],
    ['name' => 'Uganda', 'code' => '+256'],
    ['name' => 'Zambia', 'code' => '+260'],
    ['name' => 'Zimbabwe', 'code' => '+263'],

    // 🌏 Asia
    ['name' => 'Afghanistan', 'code' => '+93'],
    ['name' => 'Armenia', 'code' => '+374'],
    ['name' => 'Azerbaijan', 'code' => '+994'],
    ['name' => 'Bahrain', 'code' => '+973'],
    ['name' => 'Bangladesh', 'code' => '+880'],
    ['name' => 'Bhutan', 'code' => '+975'],
    ['name' => 'Brunei', 'code' => '+673'],
    ['name' => 'Cambodia', 'code' => '+855'],
    ['name' => 'China', 'code' => '+86'],
    ['name' => 'Georgia', 'code' => '+995'],
    ['name' => 'India', 'code' => '+91'],
    ['name' => 'Indonesia', 'code' => '+62'],
    ['name' => 'Iran', 'code' => '+98'],
    ['name' => 'Iraq', 'code' => '+964'],
    ['name' => 'Israel', 'code' => '+972'],
    ['name' => 'Japan', 'code' => '+81'],
    ['name' => 'Jordan', 'code' => '+962'],
    ['name' => 'Kazakhstan', 'code' => '+7'],
    ['name' => 'Kuwait', 'code' => '+965'],
    ['name' => 'Kyrgyzstan', 'code' => '+996'],
    ['name' => 'Laos', 'code' => '+856'],
    ['name' => 'Lebanon', 'code' => '+961'],
    ['name' => 'Malaysia', 'code' => '+60'],
    ['name' => 'Maldives', 'code' => '+960'],
    ['name' => 'Mongolia', 'code' => '+976'],
    ['name' => 'Myanmar (Burma)', 'code' => '+95'],
    ['name' => 'Nepal', 'code' => '+977'],
    ['name' => 'North Korea', 'code' => '+850'],
    ['name' => 'Oman', 'code' => '+968'],
    ['name' => 'Pakistan', 'code' => '+92'],
    ['name' => 'Palestine', 'code' => '+970'],
    ['name' => 'Philippines', 'code' => '+63'],
    ['name' => 'Qatar', 'code' => '+974'],
    ['name' => 'Saudi Arabia', 'code' => '+966'],
    ['name' => 'Singapore', 'code' => '+65'],
    ['name' => 'South Korea', 'code' => '+82'],
    ['name' => 'Sri Lanka', 'code' => '+94'],
    ['name' => 'Syria', 'code' => '+963'],
    ['name' => 'Taiwan', 'code' => '+886'],
    ['name' => 'Tajikistan', 'code' => '+992'],
    ['name' => 'Thailand', 'code' => '+66'],
    ['name' => 'Timor-Leste', 'code' => '+670'],
    ['name' => 'Turkmenistan', 'code' => '+993'],
    ['name' => 'United Arab Emirates', 'code' => '+971'],
    ['name' => 'Uzbekistan', 'code' => '+998'],
    ['name' => 'Vietnam', 'code' => '+84'],
    ['name' => 'Yemen', 'code' => '+967'],

    // 🌏 Oceanía
    ['name' => 'Australia', 'code' => '+61'],
    ['name' => 'Fiji', 'code' => '+679'],
    ['name' => 'French Polynesia', 'code' => '+689'],
    ['name' => 'Kiribati', 'code' => '+686'],
    ['name' => 'Marshall Islands', 'code' => '+692'],
    ['name' => 'Micronesia', 'code' => '+691'],
    ['name' => 'Nauru', 'code' => '+674'],
    ['name' => 'New Caledonia', 'code' => '+687'],
    ['name' => 'New Zealand', 'code' => '+64'],
    ['name' => 'Palau', 'code' => '+680'],
    ['name' => 'Papua New Guinea', 'code' => '+675'],
    ['name' => 'Samoa', 'code' => '+685'],
    ['name' => 'Solomon Islands', 'code' => '+677'],
    ['name' => 'Tonga', 'code' => '+676'],
    ['name' => 'Tuvalu', 'code' => '+688'],
    ['name' => 'Vanuatu', 'code' => '+678'],
];

// Orden: favoritos primero (si tienen 'fav'), luego alfabético por nombre
usort($countries, function($a, $b){
    $af = $a['fav'] ?? false; $bf = $b['fav'] ?? false;
    if ($af !== $bf) return $af ? -1 : 1;
    return strcasecmp($a['name'], $b['name']);
});

// prioriza old('country_code'), luego param 'selected', y por defecto +506 (CR)
$selectedCode = old('country_code', $selected ?? '+506');
@endphp

@foreach ($countries as $c)
    @php
        // acepta que te pasen el nombre o el code
        $isSelected = ($selectedCode === $c['code']) || ($selectedCode === $c['name']);
    @endphp
    <option
        value="{{ $c['code'] }}"
        data-name="{{ $c['name'] }}"
        data-code="{{ $c['code'] }}"
        {{ $isSelected ? 'selected' : '' }}
    >
        ({{ $c['code'] }}) {{ ($showNames ?? false) ? $c['name'] : '' }}
    </option>
@endforeach
