{{-- resources/views/admin/tours/partials/tab-summary.blade.php --}}

<div class="callout callout-info">
  <h5><i class="fas fa-eye"></i> {{ __('m_tours.tour.summary.preview_title') }}</h5>
  <p>
    {{ $tour
        ? __('m_tours.tour.summary.preview_text_update')
        : __('m_tours.tour.summary.preview_text_create')
    }}
  </p>
</div>

<div class="row">
  {{-- Detalles Básicos --}}
  <div class="col-md-6">
    <div class="card">
      <div class="card-header bg-primary text-white">
        <h3 class="card-title mb-0">
          <i class="fas fa-info-circle"></i> {{ __('m_tours.tour.summary.basic_details_title') }}
        </h3>
      </div>
      <div class="card-body">
        <dl class="row mb-0">
          <dt class="col-sm-4">{{ __('m_tours.tour.fields.name') }}:</dt>
          <dd class="col-sm-8" id="summary-name">
            {{ $tour->name ?? __('m_tours.tour.summary.not_specified') }}
          </dd>

          <dt class="col-sm-4">Slug:</dt>
          <dd class="col-sm-8" id="summary-slug">
            <code>{{ $tour->slug ?? __('m_tours.tour.summary.slug_autogenerated') }}</code>
          </dd>

          <dt class="col-sm-4">{{ __('m_tours.tour.fields.type') }}:</dt>
          <dd class="col-sm-8" id="summary-type">
            @if($tour && $tour->tourType)
              {{ $tour->tourType->name }}
            @else
              <span id="summary-type-text">{{ __('m_tours.tour.summary.not_specified') }}</span>
            @endif
          </dd>

          <dt class="col-sm-4">{{ __('m_tours.tour.fields.length_hours') }}:</dt>
          <dd class="col-sm-8" id="summary-length">
            {{ $tour->length ?? 'N/A' }} {{ __('m_tours.tour.summary.units.hours') }}
          </dd>

          <dt class="col-sm-4">{{ __('m_tours.tour.fields.max_capacity') }}:</dt>
          <dd class="col-sm-8" id="summary-capacity">
            {{ $tour->max_capacity ?? 'N/A' }} {{ __('m_tours.tour.summary.units.people') }}
          </dd>

          <dt class="col-sm-4">{{ __('m_tours.tour.fields.group_size') }}:</dt>
          <dd class="col-sm-8" id="summary-group-size">
            {{ $tour->group_size ?? 'N/A' }} {{ __('m_tours.tour.summary.units.people') }}
          </dd>

          <dt class="col-sm-4">{{ __('m_tours.tour.fields.status') }}:</dt>
          <dd class="col-sm-8" id="summary-status">
            @if($tour && $tour->is_active)
              <span class="badge bg-success">{{ __('m_tours.tour.status.active') }}</span>
            @else
              <span class="badge bg-secondary">{{ __('m_tours.tour.status.inactive') }}</span>
            @endif
          </dd>

          <dt class="col-sm-4">{{ __('m_tours.tour.ui.color') }}</dt>
          <dd class="col-sm-8" id="summary-color">
            <span class="badge" style="background-color: {{ $tour->color ?? '#3490dc' }}; color: #fff;">
              {{ $tour->color ?? '#3490dc' }}
            </span>
          </dd>
        </dl>
      </div>
    </div>
  </div>

  {{-- Descripción --}}
  <div class="col-md-6">
    <div class="card">
      <div class="card-header bg-info text-white">
        <h3 class="card-title mb-0">
          <i class="fas fa-align-left"></i> {{ __('m_tours.tour.summary.description_title') }}
        </h3>
      </div>
      <div class="card-body">
        <p id="summary-overview" class="mb-0">
          {{ $tour->overview ?? __('m_tours.tour.summary.no_description') }}
        </p>
      </div>
    </div>
  </div>
</div>

@if($tour ?? false)
  {{-- SOLO EN EDIT --}}
  <div class="row">
    {{-- Precios --}}
    <div class="col-md-6">
      <div class="card">
        <div class="card-header bg-success text-white">
          <h3 class="card-title mb-0">
            <i class="fas fa-dollar-sign"></i> {{ __('m_tours.tour.summary.prices_title') }}
          </h3>
        </div>
        <div class="card-body p-0">
          <table class="table table-sm mb-0">
            <thead>
              <tr>
                <th>{{ __('m_tours.tour.summary.table.category') }}</th>
                <th>{{ __('m_tours.tour.summary.table.price') }}</th>
                <th>{{ __('m_tours.tour.summary.table.min_max') }}</th>
              </tr>
            </thead>
            <tbody id="summary-prices">
              @php
                $activePrices = $tour->prices->filter(fn($p) =>
                  $p->is_active && $p->category && $p->category->is_active
                );
              @endphp
              @forelse($activePrices as $price)
                <tr>
                  <td>{{ $price->category->name }}</td>
                  <td>${{ number_format($price->price, 2) }}</td>
                  <td>{{ $price->min_quantity }}-{{ $price->max_quantity }}</td>
                </tr>
              @empty
                <tr>
                  <td colspan="3" class="text-muted text-center">
                    {{ __('m_tours.tour.summary.no_active_prices') }}
                  </td>
                </tr>
              @endforelse
            </tbody>
          </table>
        </div>
      </div>
    </div>

    {{-- Horarios --}}
    <div class="col-md-6">
      <div class="card">
        <div class="card-header bg-warning">
          <h3 class="card-title mb-0">
            <i class="fas fa-clock"></i> {{ __('m_tours.tour.summary.schedules_title') }}
          </h3>
        </div>
        <div class="card-body p-0">
          <ul class="list-group list-group-flush" id="summary-schedules">
            @forelse($tour->schedules as $schedule)
              <li class="list-group-item">
                <strong>
                  {{ date('g:i A', strtotime($schedule->start_time)) }}
                  -
                  {{ date('g:i A', strtotime($schedule->end_time)) }}
                </strong>
                @if($schedule->label)
                  <span class="badge bg-info ms-2">{{ $schedule->label }}</span>
                @endif
              </li>
            @empty
              <li class="list-group-item text-muted">
                {{ __('m_tours.tour.schedules_form.none_assigned') }}
              </li>
            @endforelse
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    {{-- Idiomas --}}
    <div class="col-md-6">
      <div class="card">
        <div class="card-header bg-secondary text-white">
          <h3 class="card-title mb-0">
            <i class="fas fa-language"></i> {{ __('m_tours.tour.summary.languages_title') }}
          </h3>
        </div>
        <div class="card-body p-0">
          <ul class="list-group list-group-flush" id="summary-languages">
            @forelse($tour->languages as $language)
              <li class="list-group-item">
                <i class="fas fa-language"></i> {{ $language->name }}
              </li>
            @empty
              <li class="list-group-item text-muted">
                {{ __('m_tours.tour.summary.no_languages') }}
              </li>
            @endforelse
          </ul>
        </div>
      </div>
    </div>

    {{-- Itinerario --}}
    <div class="col-md-6">
      <div class="card">
        <div class="card-header bg-info text-white">
          <h3 class="card-title mb-0">
            <i class="fas fa-route"></i> {{ __('m_tours.tour.summary.itinerary_title') }}
          </h3>
        </div>
        <div class="card-body">
          @if($tour->itinerary)
            <h5>{{ $tour->itinerary->name ?? __('m_tours.itinerary.fields.name') }}</h5>
            <p class="text-muted small">{{ $tour->itinerary->description }}</p>
            @if($tour->itinerary->items->isNotEmpty())
              <ol class="ps-3 mb-0">
                @foreach($tour->itinerary->items as $item)
                  <li><strong>{{ $item->title }}</strong></li>
                @endforeach
              </ol>
            @endif
          @else
            <p class="text-muted mb-0">{{ __('m_tours.tour.ui.none.itinerary') }}</p>
          @endif
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    {{-- Amenidades Incluidas --}}
    <div class="col-md-6">
      <div class="card">
        <div class="card-header bg-success text-white">
          <h3 class="card-title mb-0">
            <i class="fas fa-check"></i> {{ __('m_tours.tour.ui.amenities_included') }}
          </h3>
        </div>
        <div class="card-body p-0">
          <ul class="list-group list-group-flush" id="summary-included">
            @forelse($tour->amenities as $amenity)
              <li class="list-group-item">
                @if($amenity->icon)
                  <i class="{{ $amenity->icon }}"></i>
                @endif
                {{ $amenity->name }}
              </li>
            @empty
              <li class="list-group-item text-muted">
                {{ __('m_tours.tour.summary.none_included') }}
              </li>
            @endforelse
          </ul>
        </div>
      </div>
    </div>

    {{-- Amenidades Excluidas --}}
    <div class="col-md-6">
      <div class="card">
        <div class="card-header bg-danger text-white">
          <h3 class="card-title mb-0">
            <i class="fas fa-times"></i> {{ __('m_tours.tour.ui.amenities_excluded') }}
          </h3>
        </div>
        <div class="card-body p-0">
          <ul class="list-group list-group-flush" id="summary-excluded">
            @forelse($tour->excludedAmenities as $amenity)
              <li class="list-group-item">
                @if($amenity->icon)
                  <i class="{{ $amenity->icon }}"></i>
                @endif
                {{ $amenity->name }}
              </li>
            @empty
              <li class="list-group-item text-muted">
                {{ __('m_tours.tour.summary.none_excluded') }}
              </li>
            @endforelse
          </ul>
        </div>
      </div>
    </div>
  </div>
@else
  {{-- EN CREATE: Mensaje informativo --}}
  <div class="alert alert-info mt-3">
    <i class="fas fa-info-circle"></i>
    <strong>{{ __('m_tours.common.notice') }}</strong>
    {{ __('m_tours.tour.summary.create_note') }}
  </div>
@endif

@push('js')
<script>
document.addEventListener('DOMContentLoaded', function() {
  function updateSummary() {
    const nameInput = document.getElementById('name');
    if (nameInput) {
      const el = document.getElementById('summary-name');
      if (el) el.textContent = nameInput.value || @json(__('m_tours.tour.summary.not_specified'));
    }

    const slugInput = document.getElementById('slug');
    if (slugInput) {
      const el = document.getElementById('summary-slug');
      if (el) el.innerHTML = `<code>${slugInput.value || @json(__('m_tours.tour.summary.slug_autogenerated'))}</code>`;
    }

    const overviewInput = document.getElementById('overview');
    if (overviewInput) {
      const el = document.getElementById('summary-overview');
      if (el) el.textContent = overviewInput.value || @json(__('m_tours.tour.summary.no_description'));
    }

    const lengthInput = document.getElementById('length');
    if (lengthInput) {
      const el = document.getElementById('summary-length');
      if (el) el.textContent = (lengthInput.value || 'N/A') + ' ' + @json(__('m_tours.tour.summary.units.hours'));
    }

    const capacityInput = document.getElementById('max_capacity');
    if (capacityInput) {
      const el = document.getElementById('summary-capacity');
      if (el) el.textContent = (capacityInput.value || 'N/A') + ' ' + @json(__('m_tours.tour.summary.units.people'));
    }

    const groupSizeInput = document.getElementById('group_size');
    if (groupSizeInput) {
      const el = document.getElementById('summary-group-size');
      if (el) el.textContent = (groupSizeInput.value || 'N/A') + ' ' + @json(__('m_tours.tour.summary.units.people'));
    }

    const colorInput = document.getElementById('color');
    if (colorInput) {
      const wrap = document.getElementById('summary-color');
      if (wrap) {
        let badge = wrap.querySelector('.badge');
        if (!badge) {
          wrap.innerHTML = '<span class="badge rounded-pill">&nbsp;</span>';
          badge = wrap.querySelector('.badge');
        }
        badge.style.backgroundColor = colorInput.value || '#3490dc';
        badge.textContent = colorInput.value || '#3490dc';
      }
    }

    const activeInput = document.getElementById('is_active');
    if (activeInput) {
      const el = document.getElementById('summary-status');
      if (el) {
        el.innerHTML = activeInput.checked
          ? `<span class="badge bg-success">{{ __('m_tours.tour.status.active') }}</span>`
          : `<span class="badge bg-secondary">{{ __('m_tours.tour.status.inactive') }}</span>`;
      }
    }

    const tourTypeSelect = document.getElementById('tour_type_id');
    if (tourTypeSelect) {
      const typeText = document.getElementById('summary-type-text');
      if (typeText) {
        const selectedOption = tourTypeSelect.options[tourTypeSelect.selectedIndex];
        typeText.textContent = selectedOption?.text || @json(__('m_tours.tour.summary.not_specified'));
      }
    }
  }

  ['name','slug','overview','length','max_capacity','group_size','color','is_active','tour_type_id'].forEach(id => {
    const el = document.getElementById(id);
    if (el) {
      el.addEventListener('input',  updateSummary);
      el.addEventListener('change', updateSummary);
    }
  });

  updateSummary();
});
</script>
@endpush
