{{-- resources/views/admin/tours/partials/tab-summary.blade.php --}}

@php
  $hasTour       = isset($tour) && $tour;
  $hasItinerary  = $hasTour && $tour->itinerary;
@endphp

<div class="callout callout-info">
  <h5><i class="fas fa-eye"></i> {{ __('m_tours.tour.summary.preview_title') }}</h5>
  <p>
    {{ $hasTour
        ? __('m_tours.tour.summary.preview_text_update')
        : __('m_tours.tour.summary.preview_text_create')
    }}
  </p>
</div>

<div class="row">
  {{-- Detalles Básicos --}}
  <div class="col-md-6">
    <div class="card">
      <div class="card-header bg-primary text-white">
        <h3 class="card-title mb-0">
          <i class="fas fa-info-circle"></i> {{ __('m_tours.tour.summary.basic_details_title') }}
        </h3>
      </div>
      <div class="card-body">
        <dl class="row mb-0">
          <dt class="col-sm-4">{{ __('m_tours.tour.fields.name') }}:</dt>
          <dd class="col-sm-8" id="summary-name">
            {{ $hasTour ? $tour->name : __('m_tours.tour.summary.not_specified') }}
          </dd>

          <dt class="col-sm-4">Slug:</dt>
          <dd class="col-sm-8" id="summary-slug">
            <code>{{ $hasTour ? $tour->slug : __('m_tours.tour.summary.slug_autogenerated') }}</code>
          </dd>

          <dt class="col-sm-4">{{ __('m_tours.tour.fields.type') }}:</dt>
          <dd class="col-sm-8" id="summary-type">
            @if($hasTour && $tour->tourType)
              {{ $tour->tourType->name }}
            @else
              <span id="summary-type-text">{{ __('m_tours.tour.summary.not_specified') }}</span>
            @endif
          </dd>

          <dt class="col-sm-4">{{ __('m_tours.tour.fields.length_hours') }}:</dt>
          <dd class="col-sm-8" id="summary-length">
            {{ $hasTour
                ? ($tour->length . ' ' . __('m_tours.tour.summary.units.hours'))
                : 'N/A ' . __('m_tours.tour.summary.units.hours') }}
          </dd>

          <dt class="col-sm-4">{{ __('m_tours.tour.fields.max_capacity') }}:</dt>
          <dd class="col-sm-8" id="summary-capacity">
            {{ $hasTour
                ? ($tour->max_capacity . ' ' . __('m_tours.tour.summary.units.people'))
                : 'N/A ' . __('m_tours.tour.summary.units.people') }}
          </dd>

          <dt class="col-sm-4">{{ __('m_tours.tour.fields.group_size') }}:</dt>
          <dd class="col-sm-8" id="summary-group-size">
            {{ $hasTour
                ? ($tour->group_size . ' ' . __('m_tours.tour.summary.units.people'))
                : 'N/A ' . __('m_tours.tour.summary.units.people') }}
          </dd>

          <dt class="col-sm-4">{{ __('m_tours.tour.fields.status') }}:</dt>
          <dd class="col-sm-8" id="summary-status">
            @if($hasTour && $tour->is_active)
              <span class="badge bg-success">{{ __('m_tours.tour.status.active') }}</span>
            @else
              <span class="badge bg-secondary">{{ __('m_tours.tour.status.inactive') }}</span>
            @endif
          </dd>

          <dt class="col-sm-4">{{ __('m_tours.tour.ui.color') }}</dt>
          <dd class="col-sm-8" id="summary-color">
            <span class="badge"
                  style="background-color: {{ $hasTour ? ($tour->color ?? '#3490dc') : '#3490dc' }}; color: #fff;">
              {{ $hasTour ? ($tour->color ?? '#3490dc') : '#3490dc' }}
            </span>
          </dd>
        </dl>
      </div>
    </div>
  </div>

  {{-- Descripción --}}
  <div class="col-md-6">
    <div class="card">
      <div class="card-header bg-info text-white">
        <h3 class="card-title mb-0">
          <i class="fas fa-align-left"></i> {{ __('m_tours.tour.summary.description_title') }}
        </h3>
      </div>
      <div class="card-body">
        <p id="summary-overview" class="mb-0">
          {{ $hasTour
              ? ($tour->overview ?: __('m_tours.tour.summary.no_description'))
              : __('m_tours.tour.summary.no_description') }}
        </p>
      </div>
    </div>
  </div>
</div>

<div class="row">
  {{-- Precios --}}
  <div class="col-md-6">
    <div class="card">
      <div class="card-header bg-success text-white">
        <h3 class="card-title mb-0">
          <i class="fas fa-dollar-sign"></i> {{ __('m_tours.tour.summary.prices_title') }}
        </h3>
      </div>
      <div class="card-body p-0">
        <table class="table table-sm mb-0">
          <thead>
            <tr>
              <th>{{ __('m_tours.tour.summary.table.category') }}</th>
              <th>{{ __('m_tours.tour.summary.table.price') }}</th>
              <th>{{ __('m_tours.tour.summary.table.min_max') }}</th>
              <th>{{ __('m_tours.tour.summary.table.status') ?? '' }}</th>
            </tr>
          </thead>
          <tbody id="summary-prices-body">
            @php
              $activePrices = $hasTour
                  ? $tour->prices->filter(fn($p) => $p->category && $p->category->is_active)
                  : collect();
            @endphp
            @forelse($activePrices as $price)
              <tr>
                <td>{{ $price->category->name }}</td>
                <td>{{ config('app.currency_symbol', '$') }}{{ number_format($price->price, 2) }}</td>
                <td>{{ $price->min_quantity }}-{{ $price->max_quantity }}</td>
                <td>
                  @if($price->is_active)
                    <span class="badge bg-success">{{ __('m_tours.common.active') }}</span>
                  @else
                    <span class="badge bg-secondary">{{ __('m_tours.common.inactive') }}</span>
                  @endif
                </td>
              </tr>
            @empty
              <tr>
                <td colspan="4" class="text-muted text-center">
                  {{ __('m_tours.tour.summary.no_active_prices') }}
                </td>
              </tr>
            @endforelse
          </tbody>
        </table>
      </div>
    </div>
  </div>

  {{-- Horarios --}}
  <div class="col-md-6">
    <div class="card">
      <div class="card-header bg-warning">
        <h3 class="card-title mb-0">
          <i class="fas fa-clock"></i> {{ __('m_tours.tour.summary.schedules_title') }}
        </h3>
      </div>
      <div class="card-body p-0">
        <ul class="list-group list-group-flush" id="summary-schedules">
          @php
            $schedules = $hasTour ? $tour->schedules : collect();
          @endphp
          @forelse($schedules as $schedule)
            <li class="list-group-item">
              <strong>
                {{ date('g:i A', strtotime($schedule->start_time)) }}
                -
                {{ date('g:i A', strtotime($schedule->end_time)) }}
              </strong>
              @if($schedule->label)
                <span class="badge bg-info ms-2">{{ $schedule->label }}</span>
              @endif
            </li>
          @empty
            <li class="list-group-item text-muted">
              {{ __('m_tours.tour.schedules_form.none_assigned') }}
            </li>
          @endforelse
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="row">
  {{-- Idiomas --}}
  <div class="col-md-6">
    <div class="card">
      <div class="card-header bg-secondary text-white">
        <h3 class="card-title mb-0">
          <i class="fas fa-language"></i> {{ __('m_tours.tour.summary.languages_title') }}
        </h3>
      </div>
      <div class="card-body p-0">
        <ul class="list-group list-group-flush" id="summary-languages">
          @php
            $languages = $hasTour ? $tour->languages : collect();
          @endphp
          @forelse($languages as $language)
            <li class="list-group-item">
              <i class="fas fa-language"></i> {{ $language->name }}
            </li>
          @empty
            <li class="list-group-item text-muted">
              {{ __('m_tours.tour.summary.no_languages') }}
            </li>
          @endforelse
        </ul>
      </div>
    </div>
  </div>

  {{-- Itinerario --}}
  <div class="col-md-6">
    <div class="card">
      <div class="card-header bg-info text-white">
        <h3 class="card-title mb-0">
          <i class="fas fa-route"></i> {{ __('m_tours.tour.summary.itinerary_title') }}
        </h3>
      </div>
      <div class="card-body">
        {{-- mensaje vacío --}}
        <div id="summary-itinerary-empty"
             class="{{ $hasItinerary ? 'd-none' : '' }}">
          <p class="text-muted mb-0">
            {{ __('m_tours.tour.ui.none.itinerary') }}
          </p>
        </div>

        {{-- contenido cuando hay itinerario --}}
        <div id="summary-itinerary-content"
             class="{{ $hasItinerary ? '' : 'd-none' }}">
          <h5 id="summary-itinerary-name">
            {{ $hasItinerary ? $tour->itinerary->name : '' }}
          </h5>

          <p class="text-muted small" id="summary-itinerary-description">
            {{ $hasItinerary ? ($tour->itinerary->description ?? '') : '' }}
          </p>

          <ol class="ps-3 mb-0" id="summary-itinerary-items">
            @if($hasItinerary && $tour->itinerary->items->isNotEmpty())
              @foreach($tour->itinerary->items as $item)
                <li><strong>{{ $item->title }}</strong></li>
              @endforeach
            @endif
          </ol>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  {{-- Amenidades Incluidas --}}
  <div class="col-md-6">
    <div class="card">
      <div class="card-header bg-success text-white">
        <h3 class="card-title mb-0">
          <i class="fas fa-check"></i> {{ __('m_tours.tour.ui.amenities_included') }}
        </h3>
      </div>
      <div class="card-body p-0">
        <ul class="list-group list-group-flush" id="summary-included">
          @php
            $amenities = $hasTour ? $tour->amenities : collect();
          @endphp
          @forelse($amenities as $amenity)
            <li class="list-group-item">
              @if($amenity->icon)
                <i class="{{ $amenity->icon }}"></i>
              @endif
              {{ $amenity->name }}
            </li>
          @empty
            <li class="list-group-item text-muted">
              {{ __('m_tours.tour.summary.none_included') }}
            </li>
          @endforelse
        </ul>
      </div>
    </div>
  </div>

  {{-- Amenidades Excluidas --}}
  <div class="col-md-6">
    <div class="card">
      <div class="card-header bg-danger text-white">
        <h3 class="card-title mb-0">
          <i class="fas fa-times"></i> {{ __('m_tours.tour.ui.amenities_excluded') }}
        </h3>
      </div>
      <div class="card-body p-0">
        <ul class="list-group list-group-flush" id="summary-excluded">
          @php
            $excludedAmenities = $hasTour ? $tour->excludedAmenities : collect();
          @endphp
          @forelse($excludedAmenities as $amenity)
            <li class="list-group-item">
              @if($amenity->icon)
                <i class="{{ $amenity->icon }}"></i>
              @endif
              {{ $amenity->name }}
            </li>
          @empty
            <li class="list-group-item text-muted">
              {{ __('m_tours.tour.summary.none_excluded') }}
            </li>
          @endforelse
        </ul>
      </div>
    </div>
  </div>
</div>

@if(!$hasTour)
  <div class="alert alert-info mt-3">
    <i class="fas fa-info-circle"></i>
    <strong>{{ __('m_tours.common.notice') }}</strong>
    {{ __('m_tours.tour.summary.create_note') }}
  </div>
@endif
